version: '3.9'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bain-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=bain
      - MYSQL_DATABASE=bain

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - bain-network
    environment:
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=db
    restart: always

volumes:
  mysql-data:

networks:
  bain-network:
    driver: bridge
